name: penguins_keras
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=2.0
  - pandas>=2.2
  - matplotlib>=3.9
  - seaborn>=0.13
  - scikit-learn>=1.5
  - pip
  - pip:
      - tensorflow==2.20.0
      - joblib>=1.4
      - ipykernel>=6.29

# usage:
# conda env create -f environment.yml
# conda activate penguins_keras
